### PR TITLE
feature(slate) Lists in Slate now preserve structured content inside…

### PR DESCRIPTION
**Pull request by jeromesimeon**
… of the list items

Signed-off-by: Jerome Simeon <jeromesimeon@me.com>

# Issue #109 
This revises the behaviour of the Slate transform for lists.

Previously it only took the content of the first paragraph and discarded the rest in the `list_item` Slate node.

With this PR, it constructs any arbitrary Slate DOM within the list based on the Cicero DOM (e.g., paragraphs mapped to paragraphs, nested lists to nested lists, etc).

# Review help

It is unclear if this should be considered a bug fix or a breaking change. This definitely changes the behaviour for single paragraphs (which now have one extra Slate `paragraph` node inside list items).

# Other context

I think this could actually help with the issue here: https://github.com/accordproject/markdown-editor/issues/187
and the corresponding PR here: https://github.com/accordproject/markdown-editor/pull/188

Notably the schema should now assume the content of a list item would have the proper paragraph block -- as suggested by @dselman in comment.

### CODE REVIEW

**Comment by irmerk** [comment]
This makes sense to me. I think we would want to have this softbreak example as a test case.

**Comment by jeromesimeon** [comment]
> This makes sense to me. I think we would want to have this softbreak example as a test case.

Great idea. I'll add a test for that.

**Comment by jeromesimeon** [comment]
> This makes sense to me. I think we would want to have this softbreak example as a test case.

Added a test in https://github.com/accordproject/markdown-transform/pull/123/commits/45532a7baac213fde67294040b0cebbd446e148c

**Comment by irmerk** [comment]
As for type, I would think this is a fix rather than a breaking change.

**Comment by jeromesimeon** [comment]
> As for type, I would think this is a fix rather than a breaking change.

I'm worried some previous code relied on the fact that there was no paragraph node in the list item?

**Pull request merged**
