### PR TITLE
Add parser for OOXML transformation to CiceroMark

### PR DESCRIPTION
**Pull request by algomaster99**
Signed-off-by: Aman Sharma <mannu.poski10@gmail.com>

# Issue #247

### Changes
- [x] Add function for converting OOXML to CiceroMark with proper tests
- [ ] Add function for converting CiceroMark to OOXML with proper tests

### CODE REVIEW

**Comment by irmerk** [comment]
This replaces #251 correct?

**Comment by algomaster99** [comment]
Oh, yeah. I accidentally added the PR number there 😅
I will close #251.

**Comment by irmerk** [comment]
I think we should stick to the [AP git standard](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#-git-commit-guidelines)

**Comment by jeromesimeon** [comment]
@algomaster99 @irmerk Should this one be closed?

**Comment by algomaster99** [comment]
Closing this because PRs from forks cannot create a micro-publish on npm. Replacement PR - https://github.com/accordproject/markdown-transform/pull/263

**Pull request closed without merging**
