### PR TITLE
doc(README): centering title and badges

### PR DESCRIPTION
**Pull request by DEBSUBHRO**
Signed-off-by: DEBSUBHRO <debsubhro.roy10@yahoo.com>

# Issue #75

### Changes
* Centering the heading **Markdown-Transform**.
* Centering the corresponding badges below.

### Related Issues
- Issue #79 
- Pull Request #43

### CODE REVIEW

**Comment by mttrbrts** [comment]
Please add the DCO sign-off to this one too

**Comment by DEBSUBHRO** [comment]
> Please add the DCO sign-off to this one too

Sir, I signed it.

**Comment by irmerk** [comment]
I believe you'll need to resolve conflicts before review.

**Comment by DEBSUBHRO** [comment]
> I believe you'll need to resolve conflicts before review.

Ma'am, conflicts resolved.

**Pull request merged**
