### PR TITLE
fixes: #405 Formatted the code using prettier

### LINKED ISSUE #405: Formatter configuration
# Feature Request 🛍️

Add a formatter (prettier or any other) configuration to the codebase which is consistent with the `eslint-configuration` and introduces as few as possible linting changes.

## Use Case

Formatting the codebase with formatted will improve the spacing which will improve the readability of the code.

## Possible Solution

Can use prettier with some manual config file for the same.

## Context

While working for a PR, there occurred a need for formatting. This made this issue rise up.

## Detailed Description

The changes will most likely include:

- Addition of some new packages
- New configuration file for the formatter package.
- Changes to the existing `eslint` configuration to be consistent with existing rules along with formatting rules.

### PR DESCRIPTION
**Pull request by aashimawadhwa**
# Closes #405
formatted the code using prettier and added required packages

### Changes

 formats every `*.js` or `*.jsx` file in the “scripts/”

### Related Issues
- Issue #405

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [x] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [x] Extend the documentation, if necessary
- [x] Merging to `master` from `fork : master`

### CODE REVIEW

**Review by irmerk — CHANGES_REQUESTED** [review]
Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the --signoff option of git commit.

**Comment by aashimawadhwa** [comment]
I tried my level best to solve this , I signed all the commits but the last one is always left out , please help me out @irmerk

**Comment by irmerk** [comment]
If you're unable to solve it, I would recommend just starting a new branch and ensuring you put the signoff on the commit(s) when you begin and open a new PR.

So when you commit: `git commit --signoff -m 'INSERT TEXT'`

**Comment by aashimawadhwa** [comment]
> If you're unable to solve it, I would recommend just starting a new branch and ensuring you put the signoff on the commit(s) when you begin and open a new PR.
> 
> So when you commit: `git commit --signoff -m 'INSERT TEXT'`

should I close this PR and create a new one?

**Pull request closed without merging**
