### PR TITLE
Update DEVELOPERS.md

### PR DESCRIPTION
**Pull request by sakshamtaneja21**
# Issue #<NUMBER HERE>
<OVERALL SUMMARY OF PULL REQUEST>
fixed typos
### Changes
- <INSERT DESCRIPTION OF CHANGES>
  - <SUB NOTES OF DESCRIPTIONS>
- <SUMMARIZE ALL COMMITS IN PULL REQUEST>

### Flags
- <DESCRIBE ISSUES OR HOLDS FOR REVIEWERS>

### Related Issues
- Issue #<NUMBER HERE>
- Pull Request #<NUMBER HERE>

### CODE REVIEW

**Comment by irmerk** [comment]
These changes aren't necessary.

**Comment by sakshamtaneja21** [comment]
ok
what changes you want

**Comment by sakshamtaneja21** [comment]
also may i know when will we will receiving hactoberfest swag form 
refer : https://www.accordproject.org/events/hacktoberfest-2019/

**Comment by irmerk** [comment]
There are plenty of issues to work on which are tracked here: https://github.com/orgs/accordproject/projects/7

The event you linked describes what level of issues/PRs must be accepted for swag.

**Comment by sakshamtaneja21** [comment]
how can I get an invite of your GitHub organization as a member

**Pull request closed without merging**
