### PR TITLE
Add bootstrap

### PR DESCRIPTION
**Pull request by dlemstra**
### Changes
This PR adds `lerna bootstrap` as a postinstall step to make sure the packages are setup correctly.

### CODE REVIEW

**Comment by jeromesimeon** [comment]
@dlemstra We don't have an issue with this that I know of. Can you explain what the problem you are trying to solve is? If there is something wrong with CI, please open a new issue first. Thanks.

**Comment by dlemstra** [comment]
This is not a CI issue. I was trying to see I could fix one of the issues and I noticed that `lerna bootstrap` was not automatically executed when an `npm install` was run. This PR fixes that. The CI changes were made because running lerna bootstrap is now done automatically in npm install.

p.s. I hope you don't close every PR without even giving the contributer time to respond.

**Comment by jeromesimeon** [comment]
@dlemstra I only closed because I could not understand what this was about, as explained. It sounds like what you're talking about could be addressed by updating the documentation to clearly indicate that this is a lerna repo and to call `lerna bootstrap` not `npm install`. I believe we do that for other lerna repos we maintain: https://github.com/accordproject/cicero/blob/master/DEVELOPERS.md#building-cicero

**Comment by jeromesimeon** [comment]
@dlemstra I think we want to call `lerna bootstrap` instead of `npm install`.

**Comment by dlemstra** [comment]
Calling `lerna bootstrap` would require you to have lerna installed globaly with this setup you can use `npm install` that runs `lerna` after the packages are installed. But that is probably just a matter of preference.

**Comment by jeromesimeon** [comment]
> Calling `lerna bootstrap` would require you to have lerna installed globaly with this setup you can use `npm install` that runs `lerna` after the packages are installed. But that is probably just a matter of preference.

Fair enough. I personally like the idea of not having to install `lerna` globally. But if we go that route, this will have to go with a number of fixes/cleanup to dependencies in the top-level `package.json` along with the `postinstall` change + corresponding fixes to the documentation + changes to CI and maybe deploy scripts. This also will have to be applied systematically to all repos based on lerna.

So I think it would be worth having an issue about this first so others can comment.

**Pull request closed without merging**
