### PR TITLE
chore(build) Always call linter on testing

### PR DESCRIPTION
**Pull request by jeromesimeon**
Signed-off-by: Jerome Simeon <jeromesimeon@me.com>

# Issue #336 #335 
- Turns on linter for global `npm run test`, ensuring it is run by the CI
- Fixes linting issues for `markdown-pdf` package, including race condition on async/await
- Fixes pdf transform for headings, now can handle various kinds of content/inlines

### CODE REVIEW

**Comment by jeromesimeon** [comment]
@martinhalford Would love a review on the second commit if you can.

**Review by dselman — APPROVED** [review]
LGTM

**Review by martinhalford — COMMENTED** [review]
@jeromesimeon. This is a nice improvement. By storing changes in the updates array and then updating the key in the `foreach` loop later, we avoid any issues with erroneous updates.  However, not sure why we are using a `.then()` since we are awaiting the `Promise.all`.

**Comment by jeromesimeon** [comment]
> @jeromesimeon. This is a nice improvement. By storing changes in the updates array and then updating the key in the `foreach` loop later, we avoid any issues with erroneous updates. However, not sure why we are using a `.then()` since we are awaiting the `Promise.all`.

Thanks! I think this is still correct, since the await will apply to the combination of `Promise.all(...).then(...)` but maybe you are right that this could have been written more nicely without that `then()` by placing the result of the `Promise.all` into a variable.

The purpose of the change was essentially to avoid having multiple `object[key] = ...;` in parallel which could result in race conditions.

**Comment by martinhalford** [comment]
> Thanks! I think this is still correct, since the await will apply to the combination of `Promise.all(...).then(...)` but maybe you are right that this could have been written more nicely without that `then()` by placing the result of the `Promise.all` into a variable.
> 
> The purpose of the change was essentially to avoid having multiple `object[key] = ...;` in parallel which could result in race conditions.

You are probably right. Anyway, really good idea to avoid the race conditions. Thanks for fixing that!

**Pull request merged**
