### PR TITLE
chore(build) Adjust GitHub workflows based on latest in Concerto

### PR DESCRIPTION
**Pull request by jeromesimeon**
Signed-off-by: Jerome Simeon <jeromesimeon@me.com>

Fixes: https://github.com/accordproject/markdown-transform/issues/364

### Changes

- Update GitHub workflows to align with the latest in Concerto

### CODE REVIEW

**Review by mttrbrts — APPROVED** [review]

**Comment by mttrbrts** [comment]
@jeromesimeon it appears that these scripts are publishing to NPM in PRs, is that intended?
image

Also we seem to be getting duplicate runs, one for `push` and one for `pull_request`, presumably we only want one.

**Review by mttrbrts — CHANGES_REQUESTED** [review]
See my comment above

**Comment by jeromesimeon** [comment]
> @jeromesimeon it appears that these scripts are publishing to NPM in PRs, is that intended?
> image
> 
> Also we seem to be getting duplicate runs, one for `push` and one for `pull_request`, presumably we only want one.

I may be wrong, but what I believe happens is:
- you always get a build for a commit (i.e., push)
- you always get a build for a PR

That's always what we've done and I think makes sense?

And you get a publish on commits (i.e., push)

That's also what we've traditionally done.

**Comment by jeromesimeon** [comment]
Additional note:
- for many users we will only see PR for builds (because they will do a PR from a fork rather than a branch in the repo)
- for many users we will only see a build + publish when we merge those PRs

That's the most common scenario

**Comment by mttrbrts** [comment]
> Additional note:
> 
> * for many users we will only see PR for builds (because they will do a PR from a fork rather than a branch in the repo)
> * for many users we will only see a build + publish when we merge those PRs
> 
> That's the most common scenario

It appears that the build is publishing to NPM before the PR is merged, e.g. https://github.com/accordproject/markdown-transform/pull/365/checks?check_run_id=2149492576

**Comment by jeromesimeon** [comment]
> > Additional note:
> > 
> > * for many users we will only see PR for builds (because they will do a PR from a fork rather than a branch in the repo)
> > * for many users we will only see a build + publish when we merge those PRs
> > 
> > That's the most common scenario
> 
> It appears that the build is publishing to NPM before the PR is merged, e.g. https://github.com/accordproject/markdown-transform/pull/365/checks?check_run_id=2149492576

not really it published on commit to the branch.

**Comment by jeromesimeon** [comment]
> > Additional note:
> > 
> > * for many users we will only see PR for builds (because they will do a PR from a fork rather than a branch in the repo)
> > * for many users we will only see a build + publish when we merge those PRs
> > 
> > That's the most common scenario
> 
> It appears that the build is publishing to NPM before the PR is merged, e.g. https://github.com/accordproject/markdown-transform/pull/365/checks?check_run_id=2149492576

That PR was not from a fork.

**Review by mttrbrts — APPROVED** [review]

**Pull request merged**
